### ISSUE TITLE
make touchbackend no longer works correctly

### ISSUE THREAD

**Issue by niccolomineo** [20tab/django-continuous-delivery#13]
`Make touchbackend` no longer works, as it doesn't seem to be pointing to the correct container (whose name is now prefixed with the project name).

**Comment by pauloxnet** [comment]
The [`Makefile`](https://github.com/20tab/django-continuous-delivery/blob/master/%7B%7Bcookiecutter.project_dirname%7D%7D/Makefile) does not contain a `touchbackend` command as you can see in the file.

**Comment by niccolomineo** [comment]
Ok, then the issue appears to be related to a project that's akin to this one.
