### ISSUE TITLE
Error when `Git commit`ing

### ISSUE THREAD

**Issue by niccolomineo** [20tab/django-continuous-delivery#14]
```shell
$ git commit -a
env: python3.7: No such file or directory
```

Seems like python v 3.7 is hardcoded in the pre-commit hook.

**Comment by pauloxnet** [comment]
Actually the the definition on pre-commit is only related to python3
```
default_language_version:
    python: python3
```
https://github.com/20tab/django-continuous-delivery/blob/master/%7B%7Bcookiecutter.project_dirname%7D%7D/.pre-commit-config.yaml

**Comment by niccolomineo** [comment]
Ok, then the issue appears to be related to a project that's akin to this one.
