### ISSUE TITLE
Handle media files in tests

### ISSUE THREAD

**Issue by niccolomineo** [20tab/django-continuous-delivery#163]
What about handling test media files separately, so they do not pollute the `media` directory once tests are over?

We could do something like:

settings.py
```
class Testing(ProjectDefault):
    """The testing settings."""

    ...

    MEDIA_ROOT = ProjectDefault.BASE_DIR / "media_test"  # noqa
```

MakeFile
```
simpletest:
	...
	rm -rf media_test
```

coverage.sh
```
...
rm -rf media_test
```

Of course this should be possible only if `use_media = True`.

Am I missing any other files where this should be dealt with?

**Comment by trottomv** [comment]
I don't really like the solution of putting `rm -rf media_test/` in the Makefile after the test scripts, because if the test fails removing media is not performed, I would prefer to implement a class in a snippet `commons/tests/utils.py` like:
```
class CleanUpMediaTestCase (TestCase):
     """Define clean media for tests."""

     @classmethod
     def tearDownClass (cls):
         """Clean up after tests."""
         shutil.rmtree(settings.MEDIA_ROOT, ignore_errors=True)
         super().tearDownClass() 
```

But, to allow the media removal at the end of the test execution, this class must be inherited in the tests where are managed files.

**Comment by pauloxnet** [comment]
I agree with @trottomv that media deletion should handled in tear down phase test by test

**Comment by niccolomineo** [comment]
I see, it makes sense. Is there any chance to see this feature making it into the template (which is actually my main concern)?

**Comment by trottomv** [comment]
@pauloxnet I personally still consider it useful to set MEDIA_ROOT to `media_test` in `Testing` configurations

**Comment by pauloxnet** [comment]
Yes, open a PR with your proposal.

**Comment by niccolomineo** [comment]
@trottomv, you sound like you had the chance to reason about this quite a bit more than I did. I believe it would be better if you were the one to open the PR. What do you think?
