### ISSUE TITLE
Replace 'safety' with pip-audit

### ISSUE THREAD

**Issue by pauloxnet** [20tab/django-continuous-delivery#194]
More info: 

- code https://github.com/trailofbits/pip-audit
- package https://pypi.org/project/pip-audit/

**Comment by niccolomineo** [comment]
We should also look into [docker scan](https://docs.docker.com/engine/scan/) for docker images, as suggested at the end of a build:

![Schermata 2022-03-22 alle 15 13 26](https://user-images.githubusercontent.com/5409469/159501884-9abf7ada-9b16-4c7a-8a1a-7e02008e159e.png)
