### ISSUE TITLE
Replace PYTHONBREAKPOINT

### ISSUE THREAD

**Issue by trottomv** [20tab/django-continuous-delivery#198]
I suggest to replace `PYTHONBREAKPOINT` in `.env_template` file as follow:

`PYTHONBREAKPOINT=IPython.core.debugger.set_trace`

**Comment by pauloxnet** [comment]
Can you explain the motivations, and than open a PR ?

**Comment by trottomv** [comment]
the current configuration to `PYTHONBREAKPOINT=ipdb.set_trace` breaks debugging in tests and it is not possible to insert working breakpoints on running tests,
with setting `PYTHONBREAKPOINT=IPython.core.debugger.set_trace` it seems possible to get around the problem

**Comment by pauloxnet** [comment]
Interesting. Can you open a PR about that ?

**Comment by niccolomineo** [comment]
The problem lies in the XML runner for the tests, which we don't really need locally. I am opening a PR with a proposal.

**Comment by niccolomineo** [comment]
It should also be noted that @trottomv 's PR is actually quite useful in combination with mine. I noticed that iPython's core debugger (proposed by Matteo) works just fine if XML Runner is not set. iPython's core debugger even allows for input navigation.

**Comment by niccolomineo** [comment]
What I suggest @trottomv to do is replace `ipdb` with `ipython`, which will allow us to do away with one dependency.
