### ISSUE TITLE
Add uwsgitop in docker.ini

### ISSUE THREAD

**Issue by gabbork** [20tab/django-continuous-delivery#59]
in https://github.com/20tab/django-continuous-delivery/blob/master/%7B%7Bcookiecutter.project_dirname%7D%7D/uwsgiconf/docker.ini

we should add 
```
# Stats
stats = :9000
memory-report = 1
```
(already supported in prod.ini requirement)

and in documentation, the info to run it, when connected to django container:
```$ uwsgitop :9000```

**Comment by pauloxnet** [comment]
uWSGI is no longer used
