### ISSUE TITLE
Unbound constants in task file

### ISSUE THREAD

**Issue by niccolomineo** [20tab/django-continuous-delivery#78]
I get a couple of VSCode warnings about the `ZEROCONF` and `ZEROOPTS` constants being unbound in tasks.py.

To reproduce the issue, just open tasks.py in VSCode.

**Comment by pauloxnet** [comment]
Try to deactive all your VS code plugints and try again to open the task.py file

**Comment by niccolomineo** [comment]
It is not a matter of deactivating the plugins, unfortunately. Rather, it is logic that was overlooked in the first place and that should be implemented: the constants need to be set to some value before any `if` clause, because those `if`s only cover __some__ of the cases in which the constants can have a value.

**Comment by pauloxnet** [comment]
I don't think `ZEROCONF` and `ZEROOPTS` needs to be initialized because them are evaluated only if `EMPEROR_MODE` is true.

Anyway I checked the file in vs code 1.5.1 and ms-python plugin with no complains and also checked with flake8 and mypy.

If you still have some warnings please report your vs code version and extensios with the warnings.

**Comment by niccolomineo** [comment]
I am using VSCode 1.51 with `ms-python` and `ms-python.vscode-pylance` (the latter is the one raising the complaint). It complains that the two constants on line 62 and 63 are unbound (see the warning report below).  If you try and init those two constants to an empty string on line 32, the error goes away.

```
{
	"resource": "tasks.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "\"ZEROCONF\" is possibly unbound",
	"source": "Pylance (reportUnboundVariable)",
	"startLineNumber": 62,
	"startColumn": 38,
	"endLineNumber": 62,
	"endColumn": 46
}

{
	"resource": "tasks.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "\"ZEROOPTS\" is possibly unbound",
	"source": "Pylance (reportUnboundVariable)",
	"startLineNumber": 63,
	"startColumn": 38,
	"endLineNumber": 63,
	"endColumn": 46
}
```

**Comment by niccolomineo** [comment]
I reckon this issue can be closed as it doesn't apply anymore.
